### ISSUE TITLE
d/p/q/r stats functions

### ISSUE THREAD

**Issue by jasonserviss** [jimhester/lookup#29] opened 2018-05-29 08:52 UTC
Hello Jim,

When "looking up" the standard distribution functions in the stats package, I get the following:

`lookup::lookup('dpois')`

> function (x, lambda, log = FALSE) 
.Call(C_dpois, x, lambda, log)

As I understand it, the function that is displayed is the R function that is calling C_dpois which is the compiled (C) code that is actually performing the calculations. I had kind of expected that it would be the underlying C code that is displayed instead... This seems to also be the case for others, i.e. rnorm, runif, etc. Maybe this is due to my lack of understanding, or potentially a issue you haven't gotten around to tackling yet, but I just thought I'd let you know. I also had a look at the [R git mirror](https://github.com/wch/r-source), since you mention in the Readme that the compiled code is pulled from there, and was unable to locate the code for dpois there either (I am sure it is probably there somewhere but...). Maybe it is "hidden away" somewhere and the same reason I am struggling to find it is the same reason lookup is struggling.... 

Regards,
Jason

**Comment by jimhester** [comment] 2018-06-03 20:34
This is because recommended packages are not looked up properly, since the source is only available in the R svn mirror rather than in the CRAN mirror like non-recommended packages.

duplicate of https://github.com/jimhester/lookup/issues/16

**Closed by jimhester** 2018-06-03 20:34 UTC
